#!/bin/bash
##################################################################
# A Project of TNET Services, Inc
#
# Title:     WiFi_Check
# Author:    Kevin Reed (Dweeber)
#            dweeber.dweebs@gmail.com
# Project:   Raspberry Pi Stuff
#
# Fixes:     Marco Massari Calderone
#            marco@marcomc.com
#
# Copyright: Copyright (c) 2012 Kevin Reed <kreed@tnet.com>
#            https://github.com/dweeber/WiFi_Check
#
# Purpose:
#
# Script checks to see if WiFi has a network IP and if not
# restart WiFi
#
# Uses a lock file which prevents the script from running more
# than one at a time.  If lockfile is old, it removes it
#
# Instructions:
#
# o Install where you want to run it from like /usr/local/bin
# o chmod 0755 /usr/local/bin/WiFi_Check
# o Add to crontab
#
# Run Every 5 mins - Seems like ever min is over kill unless
# this is a very common problem.  If once a min change */5 to *
# once every 2 mins */5 to */2 ... 
#
# */5 * * * * /usr/local/bin/WiFi_Check 
#
##################################################################
# Settings
# Where and what you want to call the Lockfile
lockfile='/var/run/WiFi_Check.pid'
# Which Interface do you want to check/fix
wlan='wlan0'
IFCONFIG="/sbin/ifconfig"
PING="/bin/ping"
SERVICE="/usr/sbin/service"
IFUP="/sbin/ifup"
IFDOWN="/sbin/ifdown"
A_PUBLIC_DNS=8.8.8.8 #we will test Google Public DNS
##################################################################
echo
echo "Starting WiFi check for $wlan"
date
echo 

# Check to see if there is a lock file
if [ -e $lockfile ]; then
    # A lockfile exists... Lets check to see if it is still valid
    pid=`cat $lockfile`
    if kill -0 &>1 > /dev/null $pid; then
        # Still Valid... lets let it be...
        #echo "Process still running, Lockfile valid"
        exit 1
    else
        # Old Lockfile, Remove it
        #echo "Old lockfile, Removing Lockfile"
        rm $lockfile
    fi
fi
# If we get here, set a lock file using our current PID#
#echo "Setting Lockfile"
echo $$ > $lockfile

# The WiFi network connectivity is verified by both the ability to ping a public DNS
# and the availability of an address for the wlan devices
echo "Performing Network check for $wlan"
if $IFCONFIG $wlan | grep -q "inet addr:" && $PING -c 10 -W 5 $A_PUBLIC_DNS -q 2>&1 > /dev/null
then
    echo "Network is Okay"
else
  echo "Network connection down! Attempting reconnection."
    $IFDOWN $wlan
    sleep 5
    $IFUP --force $wlan
    $IFCONFIG $wlan | grep "inet addr"
fi

echo 
echo "Current Setting:"
$IFCONFIG $wlan | grep "inet addr:"
echo

# The Avahi daemon, responsible for the Bonjour broadcasting unexpectedly fails very frequently
# So we will relaod it at every netwirk check
sleep 3
$SERVICE avahi-daemon restart

# Check is complete, Remove Lock file and exit

rm $lockfile
exit 0

##################################################################
# End of Script
##################################################################
